config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "mypage" => 'mypages#show', as: 'mypage'

  get 'articles/index'
  get 'articles/show'
  get 'articles/new'
  get 'articles/create'
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user



  def self.search(search)
    if search
      Article.where(["title LIKE?", "%#{search}%"])
    else
      Article.all
    end
  end


  has_many :tag_articles, dependent: :destroy
  has_many :tags, through: :tag_articles

  accepts_nested_attributes_for :tag_articles, allow_destroy: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :tag_articles, dependent: :destroy
  has_many :articles, through: :tag_articles

  accepts_nested_attributes_for :tag_articles, allow_destroy: true
end

app/models/tag_article.rb
class TagArticle < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def new
  end

  def edit
  end

  def destroy
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.all.page(params[:page]).search(params[:title])
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "記事を作成しました！" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "記事を更新しました！" }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.user_id = current_user.id

    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "記事を削除しました！" }
      format.json { head :no_content }
    end
  end



  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, tag_ids: [])
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!, only: [:mypage]

  def mypage
    redirect_to mypage_path(current_user)
  end

  def show
    @articles = Article.where(user_id: current_user).page(params[:page]).search(params[:title])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count %> 件のエラーが発生しました</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="mb-3">
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>







  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<h1>記事の更新</h1>

<%= render 'form', article: @article %>

<%= link_to '詳細', @article %> |
<%= link_to '戻る', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>

<%= render partial: "search" %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name %></span>
          <% end %>
        </td>




        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= paginate @articles, theme: 'twitter-bootstrap-4'%>

app/views/articles/new.html.erb
<h1>新規記事</h1>

<%= render 'form', article: @article %>

<%= link_to '戻る', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
      <% @article.tags.each do |tag| %>
        <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
      <% end %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>



<%= link_to '一覧', articles_path, class: "btn btn-secondary" %>


<% if user_signed_in? && @article.user_id == current_user.id %>
  <%= link_to '編集', edit_article_path(@article), class: "btn btn-warning" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "TOP", root_path %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", "/mypage" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to "サインアップ", new_user_registration_path, class: 'post' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

app/views/mypage/show.html.erb
<h1>Mypage#show</h1>
<p>Find me in app/views/mypage/show.html.erb</p>

app/views/mypages/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypages/show.html.erb
  <h1>マイページ</h1>

<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>


<%= render partial: "search" %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
        </td>





        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
        <td><%= link_to '編集', edit_article_path(article), class: "btn btn-info" %></td>
        <td><%= link_to '削除', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>









<%= paginate @articles, theme: 'twitter-bootstrap-4'%>